# Pre-commit configuration file
# See https://pre-commit.com for more information
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python-specific hooks (remove if not using Python)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        line_length: 100

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203,W503"]

  # Markdown linting
#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.35.0
#    hooks:
#      - id: markdownlint
#        args: ['--fix']


# Global configuration
default_language_version:
  python: python3.11


# Exclude files/directories
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    venv/|
    node_modules/|
    build/|
    dist/|
    \.pytest_cache/|
    __pycache__/
  )$
