[project]
name = "evosite3d"
version = "0.1"
requires-python = ">=3.9"
dependencies = [
    "biopython>=1.85",
    "matplotlib",
    "pandas",
    "scipy",
    "statsmodels",
    "seaborn"
]

[project.optional-dependencies]
dev = [
    "black>=23.0.0",
    "flake8>=7.3.0",
    "mypy>=1.5.0",
    "pylint>=3.0.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[tool.pylint.format]
max-line-length = "100"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
